"""add email_verified_at to users

Revision ID: 1aa789ccd79a
Revises: 573f7187c750
Create Date: 2026-05-02 16:27:23.118570

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1aa789ccd79a"
down_revision: Union[str, None] = "573f7187c750"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###

    # 既存の Google 認証済みユーザー（google_sub が設定済み）は
    # 過去に Google OAuth で認証されたため、email_verified_at を現在時刻で埋める
    op.execute(
        "UPDATE users SET email_verified_at = NOW() "
        "WHERE google_sub IS NOT NULL AND email_verified_at IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified_at")
    # ### end Alembic commands ###
