"""add_records_table

Revision ID: c1a2b3c4d5e6
Revises: b3f1c2d4e5f6
Create Date: 2026-01-27 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1a2b3c4d5e6"
down_revision: Union[str, None] = "b3f1c2d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "records",
        sa.Column("id", sa.String(length=30), nullable=False),
        sa.Column("week_id", sa.String(length=30), nullable=False),
        sa.Column("task_id", sa.String(length=30), nullable=False),
        sa.Column(
            "day_of_week",
            sa.Enum(
                "monday",
                "tuesday",
                "wednesday",
                "thursday",
                "friday",
                "saturday",
                "sunday",
                name="day_of_week_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "actual_units",
            sa.Numeric(precision=6, scale=1, asdecimal=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            onupdate=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("actual_units >= 0", name="ck_records_actual_units_non_negative"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"]),
        sa.ForeignKeyConstraint(["week_id"], ["weeks.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_records_task_id"), "records", ["task_id"], unique=False)
    op.create_index(op.f("ix_records_week_id"), "records", ["week_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_records_week_id"), table_name="records")
    op.drop_index(op.f("ix_records_task_id"), table_name="records")
    op.drop_table("records")
    op.execute("DROP TYPE day_of_week_enum")
    # ### end Alembic commands ###
