from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metadata", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--body-file", required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    metadata = json.loads(Path(args.metadata).read_text())

    prompt = f"""Use the pr-review agent for this task.

Review context has already been generated by the workflow.
The local working tree is the trusted `{metadata["trusted_ref"]}` checkout, not the PR head.

Use these access rules while reviewing:
- PR head version of a changed file: `git show {metadata["head_sha"]}:path/to/file`
- Base version of a changed file: `git show {metadata["base_sha"]}:path/to/file`
- Diff for the review target: `cat tmp/review/diff.patch`
- Unchanged supporting code and docs: read from the local workspace

Review steps:
1. Read `tmp/review/pr-metadata.json`
2. Read `tmp/review/context.json`
3. Read the required docs in `tmp/review/required-docs/`
4. Review the PR according to `.github/agents/pr-review.agent.md` from the trusted workspace
5. Output JSON only and follow the agent output schema exactly

Do not output markdown. Do not output explanations outside JSON.
"""
    Path(args.output).write_text(prompt)


if __name__ == "__main__":
    main()
