from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metadata", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--body-file", required=True)
    parser.add_argument("--rules", default=None)
    return parser.parse_args()


def load_rules(rules_path: str | None) -> list[dict]:
    if rules_path is None:
        return []
    path = Path(rules_path)
    if not path.exists():
        return []
    try:
        rules = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return []
    return rules if isinstance(rules, list) else []


def build_rules_section(rules: list[dict]) -> str:
    if not rules:
        return ""
    lines = [
        "",
        "## 追加レビュー観点（蓄積済みルール）",
        "",
        "以下のルールを追加の観点として確認してください。",
        "ルールに基づいて指摘を行った場合は、その指摘の `applied_rule_ids` フィールドに対応する `rule_id` を含めてください。",
        "リストにない `rule_id` は絶対に使用しないでください。",
        "",
    ]
    for rule in rules:
        rule_id = rule.get("rule_id", "")
        name = rule.get("name", "")
        category = rule.get("category", "")
        body = rule.get("body", "")
        if not rule_id or not body:
            continue
        lines.append(f"- [RuleId: {rule_id}] ({category}) {name}: {body}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    metadata = json.loads(Path(args.metadata).read_text())
    rules = load_rules(args.rules)
    rules_section = build_rules_section(rules)

    base_prompt = f"""Use the pr-review agent for this task.

Review context has already been generated by the workflow.
The local working tree is the trusted `{metadata["trusted_ref"]}` checkout, not the PR head.

Use these access rules while reviewing:
- PR head version of a changed file: `git show {metadata["head_sha"]}:path/to/file`
- Base version of a changed file: `git show {metadata["base_sha"]}:path/to/file`
- Diff for the review target: `cat tmp/review/diff.patch`
- Unchanged supporting code and docs: read from the local workspace

Review steps:
1. Read `tmp/review/pr-metadata.json`
2. Read `tmp/review/context.json`
3. Read the required docs in `tmp/review/required-docs/`
4. Review the PR according to `.github/agents/pr-review.agent.md` from the trusted workspace
5. Output JSON only and follow the agent output schema exactly

Do not output markdown. Do not output explanations outside JSON.
"""
    Path(args.output).write_text(base_prompt + rules_section)


if __name__ == "__main__":
    main()
