version = 0.1

[default.global.parameters]
stack_name = "tasche-frontend"
region = "ap-southeast-1"

# dev 環境
[dev.deploy.parameters]
stack_name = "dev-tasche-frontend"
region = "ap-southeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = [
    "Env=dev",
    "BackendFunctionUrl=/tasche/dev/sam/backend-function-url",
    "Domain=dev.tasche.life",
    "AcmCertificateArn={{resolve:ssm:/tasche/dev/frontend/acm-certificate-arn}}",
    "HostedZoneId={{resolve:ssm:/tasche/dev/frontend/hosted-zone-id}}",
]

# prod 環境 (枠のみ; 別タスクで完成させる)
[prod.deploy.parameters]
stack_name = "prod-tasche-frontend"
region = "ap-southeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
parameter_overrides = [
    "Env=prod",
    "BackendFunctionUrl=/tasche/prod/sam/backend-function-url",
]
