version = 0.1

# 共通設定
[default.global.parameters]
stack_name = "tasche-backend"
region = "ap-southeast-1"

[dev.global.parameters]
region = "ap-southeast-1"

# dev 環境
[dev.deploy.parameters]
stack_name = "dev-tasche-backend"
region = "ap-southeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "Env=dev AppEnv=development LogLevel=debug GoogleOAuthRedirectUris=https://d24uwhdoe5bq1j.cloudfront.net/auth/callback CloudFrontDistributionId=E1QVS9ESSNDTIH"
resolve_image_repos = true
resolve_s3 = true

[prod.global.parameters]
region = "ap-southeast-1"

# prod 環境 (枠のみ; 別タスクで完成させる)
[prod.deploy.parameters]
stack_name = "prod-tasche-backend"
region = "ap-southeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
parameter_overrides = "Env=prod AppEnv=production LogLevel=info"
resolve_image_repos = true
resolve_s3 = true
